name: Push Docker Image To ECR.

description: Pushing an image to docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Deploy to AWS
      run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Authenticating Docker client to AWS ECR Registry 
      run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}
    - name: check 1
      run: docker build -t ${{ github.sha }} ./app
    - name: Tagging image to ECR repo
      run: docker tag ${{ github.sha }} ${{ secrets.ECR_REPOSITORY }}:tag
    - name: Docker push
      run: docker push ${{ secrets.ECR_REPOSITORY }}:tag
