name: Push Docker Image To ECR

description: Pushing an image to docker

inputs:
  docker_imageid:
    type: string
    required: true

on:
  push:
    branches:
      - main

jobs:
  build:
    runs on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: login to docker
      run: docker login --username ${{ secrets.DOCKER_USER }} --password ${{ secrets.DOCKER_PASS }}