name: Running a Terraform Apply

on:
  workflow_dispatch:

env:
  
  AWS_REGION : "eu-west-2"

 
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  compile:
    uses: ./.github/workflows/terraformplan-pipeline.yml
  

  TerraformApply:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
        with:
          submodules: recursive 

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::291759414346:role/GitHubActionsTerraformRole
          role-session-name: GitHubActionsTerraformRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Running Terraform commands
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.14.3"

      - name: Running a Terraform Init  
        run: terraform -chdir=ecs init

      - name: Downloading Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: path/to/artifacts

      - name: Running a Terraform Apply
        run: |
          cd path/to/artifacts 
          terraform -chdir=ecs apply -auto-approve tfplan
        

