name: Running a Terraform Plan

on:
  workflow_dispatch:

env:
  AWS_REGION : "eu-west-2"

permissions:
      id-token: write  
      contents: read   

jobs:
  TerraformPlan:
    runs-on: ubuntu-24.04
    steps:

      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::291759414346:role/GitHubActionsTerraformRole
          role-session-name: GitHubActionsTerraformRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Running Terraform commands
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.14.3"

      - name: Running a Terraform Init  
        run: terraform -chdir=ecs init

      - name: Running a Terraform Plan
        run: terraform -chdir=ecs plan -out=tfplan
      
      - name: Uploading Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ./
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14.2'

      - name: Terraform Plan (Checkov)
        run: |
          pip install checkov
          terraform -chdir=ecs plan -out my-tf.plan
          terraform -chdir=ecs show -json my-tf.plan | jq '.' > my-tf.json
          checkov -f my-tf.json --quiet

