name: Running a Terraform Plan

on:
  workflow_dispatch:

env:
  AWS_REGION : "eu-west-2"

permissions:
      id-token: write  
      contents: read   

jobs:
  TerraformPlan:
    runs-on: ubuntu-24.04
    steps:

      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::291759414346:role/GitHubActionsTerraformRole
          role-session-name: GitHubActionsTerraformRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Running Terraform commands
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.14.3"

      - name: Running a Terraform Init  
        run: terraform -chdir=ecs init

      - name: Running a Terraform Plan
        run: terraform -chdir=ecs plan -out=tfplan
      
      - name: Uploading Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ./

      - name: Terraform Plan (json)
        run: terraform plan -out=tfplan.bin && terraform show -json tfplan.bin > tfplan.json

      - name: Run Checkov on plan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ./
          file: tfplan.json
          framework: terraform_plan
          soft_fail: false
          output_format: sarif
          output_file_path: checkov.sarif

      - name: Upload SARIF (Checkov)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov.sarif       



